version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pki-2fa-app

    ports:
      - "8080:8080"

    environment:
      TZ: UTC

    volumes:
      - seed-data:/data

      - cron-output:/cron

      - ./keys/student_private.pem:/usr/src/app/keys/student_private.pem:ro
      - ./keys/student_public.pem:/usr/src/app/keys/student_public.pem:ro
      - ./keys/instructor_public.pem:/usr/src/app/keys/instructor_public.pem:ro
      - ./keys/encrypted_seed.txt:/usr/src/app/keys/encrypted_seed.txt:ro

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
